; Settings for the time chime script.
;
; Available settings include the following:
; sound - Name of main chime sound file in the "sounds/" folder.
; sound2 - If nonempty, alternates between playing chimes using "sound" and
;	"sound2" as the sound files.
; interval - Time between chimes (in seconds).
; interval2 - If nonempty, alternates between playing chimes between "interval"
;	seconds and "interval2" seconds.
; cutoff - Maximum number of chimes before automatically stopping.

[settings]
sound = chime.wav
sound2 = chime2.wav
interval = 30
interval2 = 15
cutoff = 100
